[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True
check_untyped_defs = False

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-eccodes.*]
ignore_missing_imports = True